name: qr_provider
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barcode: ^2.2.8
  dart_frog: ^1.1.0
  image: ^4.5.2
  qr: ^3.0.2

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
